### ISSUE TITLE
Spaces and apostrophes in names cause problems

### ISSUE THREAD

**Issue by stiliyan** [boardPro43119/chat-server#4]
See screenshot for details. Any ideas what may be causing this? How can you fix it?

![screen shot 2015-03-07 at 2 14 49 pm](https://cloud.githubusercontent.com/assets/835142/6542837/5946c638-c4d4-11e4-9553-8ff203682680.png)

**Comment by boardPro43119** [comment]
I have discovered that when someone includes a space in their username, the "is typing" message does not disappear on other clients' screens when they submit a message.  Additionally, users with an apostrophe in their name cause the same problem plus their messages do not even get displayed to anyone upon submission.  Any ideas on how to fix this?
