### ISSUE TITLE
I can't see my friends' messages

### ISSUE THREAD

**Issue by stiliyan** [boardPro43119/chat-server#6]
Hi there,

I feel out of the loop using the chat sometimes, because when I join the chat after my friends have been talking for a while, I can't see their messages! 

Is there a way to make the server show me the last 10-15 messages when I join?

Thanks a ton!

**Comment by boardPro43119** [comment]
Here are my thoughts on how to approach fixing this issue:

- Add Redis client to server
- Create Redis list for messages
- When they send a message, `lpush` and `JSON.stringify` an object with properties name and message
- When someone signs in, display last 10-15 messages from this list on their screen (use `lrange` and `JSON.parse` each message object)

Thank you for pointing this out!

**Comment by boardPro43119** [comment]
Update: I have made a commit that allows users when they sign in to see messages sent prior to them signing in.  However, when the server is refreshed, this does not work; I am planning to implement Redis to make this fix.
